const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const DATASET_STATUS = {
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

const ISSUE_TYPES = {
  MISSING_VALUES: 'MISSING_VALUES',
  DUPLICATES: 'DUPLICATES',
  INVALID_TYPE: 'INVALID_TYPE',
  INVALID_DATE: 'INVALID_DATE',
  OUTLIER: 'OUTLIER',
  INCONSISTENT_CATEGORY: 'INCONSISTENT_CATEGORY',
  EMPTY_COLUMN: 'EMPTY_COLUMN',
  CONSTANT_COLUMN: 'CONSTANT_COLUMN',
};

const SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const DETECTED_TYPES = ['integer', 'float', 'string', 'boolean', 'datetime', 'unknown'];

module.exports = {
  ROLES,
  DATASET_STATUS,
  ISSUE_TYPES,
  SEVERITY,
  DETECTED_TYPES,
};
